### PR TITLE
Change French timplace names to English.

### PR DESCRIPTION
**Pull request by willtheorangeguy**
It makes it easier to read for people that speak English.
Just a suggestion. Doesn't have to be merged.

### CODE REVIEW

**Comment by sdispater** [comment]
I see what you mean. It was here to show that passing a `locale` keyword is possible. But changing the name of the locale to `en` works to.
If you can update the name from `fr` to `en` I can merge your PR :-)

**Comment by willtheorangeguy** [comment]
Sure I'll do that too. Is it okay if I make it as a separate PR?

**Comment by willtheorangeguy** [comment]
I made it a new PR.

**Comment by sdispater** [comment]
You can just make a new commit on your branch and push it. The PR will update automatically.

**Comment by sdispater** [comment]
No problem.

**Comment by willtheorangeguy** [comment]
Can you do the other one also?

**Comment by sdispater** [comment]
It's done

**Comment by willtheorangeguy** [comment]
Thanks!

**Pull request merged**
