### PR TITLE
Update typing comments

### PR DESCRIPTION
**Pull request by migonzalvar**
This Pull Request adds typing comments to methods that already had docstring return type annotations.

### CODE REVIEW

**Comment by harahu** [comment]
Would love to see this merged.

**Comment by Secrus** [comment]
We have migrated from type comments to type annotations. Please migrate code in this PR accordingly, then it can be considered a merge candidate.

**Comment by gandhis1** [comment]
@migonzalvar This PR is a very low-hanging fruit - are you intending to revisit this? If not, I will. Thanks

**Comment by migonzalvar** [comment]
@gandhis1 , no I won't. Please, go for it.

**Pull request closed without merging**
