### PR TITLE
added tr locale

### PR DESCRIPTION
**Pull request by mazlum**
I have added Turkish locale files.

### CODE REVIEW

**Comment by sdispater** [comment]
Thanks for your contribution!

You need to fix the linting and add tests for the added locale.

Also, can you rebase your PR on `master`?

**Comment by mazlum** [comment]
Hi,
I have added test file for Turkish file.

**Comment by sdispater** [comment]
Thanks @mazlum!

However, I think your rebase went wrong since your PR includes every commit since your initial commit it seems.

**Comment by mazlum** [comment]
So, what should I do?

**Comment by hakkikonu** [comment]
we're waiting for this PR merge :)

**Comment by Secrus** [comment]
As this got stuck in rebase hell, I made a new PR extracting only code for `tr` locale #638. Closing.

**Pull request closed without merging**
