### PR TITLE
Add Norwegian locales

### PR DESCRIPTION
**Pull request by maedox**
Norway has two locales, bokmål (nb) and Nynorsk (nn). This adds both with tests.

### CODE REVIEW

**Comment by maedox** [comment]
That went well... Tests run successfully locally on Python 3.7 at least.
I suppose the problem is elsewhere as it fails on poetry install.

**Comment by maedox** [comment]
Is anyone there?

**Comment by sdispater** [comment]
Sorry for the delay.

Could you rebase your PR so that we make sure that the tests pass?

**Comment by maedox** [comment]
Hi. I'm back! Sorry, I forgot all about this until I needed a NO locale again.
I have rebased and it still fails.

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
