### PR TITLE
Fix the release workflow

### PR DESCRIPTION
**Pull request by sdispater**
For the release workflow to work, we need to install the Rust toolchain first on some platforms and we need to use Python 3 to fix the wheels for MacOS arm wheels.

## Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by Secrus** [comment]
what about linux aarch64 wheels? maybe we could copy `coverage` setup? https://github.com/nedbat/coveragepy/blob/c2b238e86cade2e6163b24656a7d0549f4508e8f/.github/workflows/kit.yml#L101

**Comment by sdispater** [comment]
@Secrus We can always add the `aarch64` architecture but I don't know if we will need the same fixes as the ones needed for MacOS due to https://github.com/python-poetry/poetry/issues/7107.

**Comment by Secrus** [comment]
@sdispater I just thought it's worth adding and checking since you are already working on the release pipeline. Especially since there was a PR/request for that architecture for some time now: #517 #521

**Comment by edgarrmondragon** [comment]
Since this project seems to use maturin as a build, did you folks consider using the auto-generated CI build workflow?

```
maturin generate-ci github > .github/workflows/CI.yml
```

**Pull request merged**
