### PR TITLE
Add wheel support for aarch64

### PR DESCRIPTION
**Pull request by odidev**
Added wheel support for aarch64.
Related to #517  .

### CODE REVIEW

**Comment by odidev** [comment]
@sdispater, could you please have a look at this PR?

**Comment by odidev** [comment]
@sdispater, could you please take a look into this PR? Thanks.

**Comment by odidev** [comment]
@sdispater, could you please take a look into this PR? Thanks.

**Comment by odidev** [comment]
@sdispater, could you please take a look?

**Comment by odidev** [comment]
@sdispater, could you please take a look? Thanks in advance.

**Comment by spacemanspiff2007** [comment]
Would this also fix #504 or is this another issue?

**Comment by odidev** [comment]
No, its for ARMv8.

**Comment by odidev** [comment]
@sdispater, Could you please review this PR?

**Comment by edgarrmondragon** [comment]
AFAICT this is as easy as setting `CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"` in the cibuildwheel workflow

**Pull request closed without merging**
