### PR TITLE
New Parser Behavior for ":" separator in date formats

### PR DESCRIPTION
**Pull request by emattiza**
Per sdispater/pendulum#101, implements exif format (: as separator in date formats) to regex parser

- [x] Add functional test for new expected parse functionality
- [x] Test COMMON regex alteration against prior test suite

### CODE REVIEW

**Comment by sdispater** [comment]
I like it!

However, I don't see it as a bugfix but rather as a new feature (parsing of exif format), so it might be better to base this on the `develop` branch which is where new, non-breaking feature should be.

**Comment by SethMichaelLarson** [comment]
Agreed.

**Comment by emattiza** [comment]
cleaned up and rebased onto develop. Appreciate the feedback guys!

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
