### PR TITLE
Added JA translation

### PR DESCRIPTION
**Pull request by za**
## Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

Added JA translation.

### CODE REVIEW

**Comment by Secrus** [comment]
@za please fix tests and pre-commit issues. Also, the code for Japan should be `JP`, not `JA`, so please fix this accordingly.

**Comment by za** [comment]
Hi @Secrus I've reformatted using black and now it's passed. Can you give me hint about the `isort` pre-commit check? 

```
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /code/tests/localization/test_ja.py
Skipped 70 files
```

I am following the other test file and we're only importing one module which is `pendulum`.

**Comment by Secrus** [comment]
pre-commit.ci autofix

**Review by Secrus — APPROVED** [review]

**Comment by za** [comment]
Thanks for the review and merging the PR @Secrus !

**Pull request merged**
