### PR TITLE
Added __eq__ and __hash__ to Period

### PR DESCRIPTION
**Pull request by mshuffett**
This pull request solves #206 by adding __eq__ and __hash__ to Period.

### CODE REVIEW

**Comment by Marlysson** [comment]
Why does use the hash method if you can just use the __eq__ method comparing some attributes?

**Comment by sdispater** [comment]
@Marlysson Implementing the __hash__ method makes it possible to use Period obkects has key in a dictionnary for example.

**Comment by sdispater** [comment]
@mshuffett Thanks!

**Comment by Marlysson** [comment]
@sdispater But if the Period object doesn't wasn't used in a dictionary , the hash method, still would be necessary?

**Comment by sdispater** [comment]
@Marlysson In this case, no. Equality (`==`) is just checked with the `__eq__` method.

**Pull request merged**
