### PR TITLE
Add RU locale

### LINKED ISSUE #227: Porting RU locale from 1.x
Do you have plans on porting locales (formerly known as `lang` in 1.x)?

**upd.**
Trying [this ](https://github.com/sdispater/pendulum#localization) thing out and will make a PR.

### PR DESCRIPTION
**Pull request by Senpos**
Closes #227 

`locale.py` generated with `clock` on **Windows 10**.
Tests are included.

Tested by me on **Windows 10** with Python **3.6.4**.

Thanks to @creazero for testing on **Kubuntu 17.10**  with Python **2.7** and **3.6.3**.

Seems to be working fine. If you encounter any problems - feel free to update related issue or this PR.

### CODE REVIEW

**Comment by Senpos** [comment]
Due to the [Changelog](https://github.com/sdispater/pendulum/releases/tag/2.0.0):
```
diff_for_humans() now returns a few seconds where appropriate.
```

Is it now required for translations as well? 

As I can see, not all current translations use this feature, but it is quite easy to implement with:

```python3
translations = {
    ...
    'units': {
        'few_second': 'a few seconds'
    },
    ...
```

Am I right?

**Comment by Senpos** [comment]
@sdispater 

Hello.

Do I have to change something here, so you could merge it?

The only failing thing is `codecov`, but it seems like there is nothing related to my changes.

**Comment by snurbol** [comment]
@sdispater 
I agree, why you could merge it?
Failed only coverage, and tests are same as yours.

**Comment by andreynovikov** [comment]
Any chance of it to be merged? @sdispater why are you asking for locale contribution and the do not accept them for almost a year?

**Comment by sdispater** [comment]
Thanks! And sorry for the delay

**Pull request merged**
